module

public import Mathlib.Algebra.Category.ModuleCat.Sheaf.Quasicoherent
public import Mathlib.Algebra.Category.ModuleCat.Sheaf.Generators
public import Mathlib.ProjectCoherent.Instances
public import Mathlib.Algebra.Category.ModuleCat.Sheaf
public import Mathlib.CategoryTheory.Abelian.Subcategory
public import Mathlib.Algebra.Category.ModuleCat.Sheaf.Abelian

@[expose] public section

open CategoryTheory

universe w u v' u'

variable {C : Type u'} [Category.{v'} C] {J : GrothendieckTopology C} {R : Sheaf J RingCat.{u}}
  (M : SheafOfModules R)
  [HasWeakSheafify J AddCommGrpCat.{u}]
  [J.WEqualsLocallyBijective AddCommGrpCat.{u}]
  [∀ X, HasWeakSheafify (J.over X) AddCommGrpCat.{u}]
  [∀ X, (J.over X).WEqualsLocallyBijective AddCommGrpCat.{u}]

/-- The type of sections which doesn't necessarily generate a sheaf of modules. -/
structure SheafOfModules.Sections where
  /-- the index type for the sections -/
  I : Type u
  /-- a family of sections which doesn't necessarilty generate the sheaf of modules -/
  s : I → M.sections

/-- The data of sections of the restriction of a sheaf of modules
over a covering of the terminal object. -/
structure SheafOfModules.LocalSectionData where
  /-- the index type of the covering -/
  I : Type w
  /-- a family of objects which cover the terminal object -/
  X : I → C
  coversTop : J.CoversTop X
  /-- the data of sections of `M` over `X i` -/
  sections (i : I) : (M.over (X i)).Sections

/-- `σ : M.Sections` is finite type if the index type `σ.I` is finite. -/
class SheafOfModules.Sections.IsFiniteType (σ : M.Sections) : Prop where
  finite : Finite σ.I := by infer_instance

class SheafOfModules.LocalSectionData.IsFiniteType (p : M.LocalSectionData) : Prop where
  isFiniteType (i : p.I) : (p.sections i).IsFiniteType := by infer_instance

/-- The epimorphism `free σ.I ⟶ M` given by `σ : M.GeneratingSections`. -/
noncomputable abbrev SheafOfModules.Sections.π (σ : M.Sections) :=
  M.freeHomEquiv.symm σ.s

/-- A sheaf of modules is of finite type if locally, it is generated by finitely
many sections. -/
class SheafOfModules.IsCoherent (M : SheafOfModules.{u} R) : Prop where
  finiteType : M.IsFiniteType
  forall_localSectionData (M) : --todo: should we combine the foralls?
    ∀ σ : M.LocalSectionData.{u'}, (∀ i, (σ.sections i).IsFiniteType) →
      ∀ i, (Limits.kernel (σ.sections i).π).IsFiniteType

variable (R) in
def cohProp : CategoryTheory.ObjectProperty (SheafOfModules.{u} R) := by
  intro M
  exact M.IsCoherent

variable [HasSheafify J AddCommGrpCat.{u}]

variable {M} in
theorem foo (h : Limits.IsZero M) (Y : C) : Limits.IsZero (M.over Y) := sorry

theorem foo1 {M N : SheafOfModules.{u} R} (iso : M ≅ N) [M.IsFiniteType] :
N.IsFiniteType := sorry

instance (X : C) : HasSheafify (J.over X) AddCommGrpCat := sorry

instance (I : Type u) [Finite I] : (SheafOfModules.free (C := C) (J := J)
(R := R) I).IsFiniteType := sorry

noncomputable instance : (cohProp R).ContainsZero where
  exists_zero := by
    have keyfact : ∃ M : SheafOfModules R, Limits.IsZero M := by
      exact CategoryTheory.Limits.HasZeroObject.zero
    obtain ⟨M,hM⟩:= keyfact
    use M
    constructor
    · exact hM
    · constructor
      · constructor
        let σ : M.LocalGeneratorsData :=
            { I := C
              X := id
              coversTop c := by
                simp
              generators i :=
              { I := PEmpty
                s := PEmpty.elim
                epi := by
                  apply Limits.IsZero.epi
                  exact foo hM i}
            }
        use σ
        constructor
        intro i
        refine ⟨?_⟩
        dsimp [σ]
        infer_instance
      intro σ' h i'
      let iso : SheafOfModules.free (σ'.sections i').I ≅
        Limits.kernel (SheafOfModules.Sections.π (M.over (σ'.X i'))
         (σ'.sections i')) := by
          convert Limits.kernelZeroIsoSource.symm
          apply Limits.IsZero.eq_zero_of_tgt
          exact foo hM _
      have : Finite (σ'.sections i').I := h i' |>.finite
      apply foo1 iso

noncomputable instance : (cohProp R).IsClosedUnderKernels := by
  sorry

noncomputable instance : (cohProp R).IsClosedUnderCokernels := by
  sorry

noncomputable instance : (cohProp R).IsClosedUnderFiniteProducts := by
  sorry

noncomputable instance : Abelian (cohProp R).FullSubcategory := by
  infer_instance

end
