module

public import Mathlib.Algebra.Category.ModuleCat.Sheaf.Quasicoherent
public import Mathlib.Algebra.Category.ModuleCat.Sheaf.Generators
public import Mathlib.ProjectCoherent.Instances
public import Mathlib.Algebra.Category.ModuleCat.Sheaf
public import Mathlib.CategoryTheory.Abelian.Subcategory
public import Mathlib.Algebra.Category.ModuleCat.Sheaf.Abelian

@[expose] public section

open CategoryTheory

universe w u v' u'

variable {C : Type u'} [Category.{v'} C] {J : GrothendieckTopology C} {R : Sheaf J RingCat.{u}}
  (M : SheafOfModules R)
  [HasWeakSheafify J AddCommGrpCat.{u}]
  [J.WEqualsLocallyBijective AddCommGrpCat.{u}]
  [∀ X, HasWeakSheafify (J.over X) AddCommGrpCat.{u}]
  [∀ X, (J.over X).WEqualsLocallyBijective AddCommGrpCat.{u}]

/-- The type of sections which doesn't necessarily generate a sheaf of modules. -/
structure SheafOfModules.Sections where
  /-- the index type for the sections -/
  I : Type u
  /-- a family of sections which doesn't necessarilty generate the sheaf of modules -/
  s : I → M.sections

/-- The data of sections of the restriction of a sheaf of modules
over a covering of the terminal object. -/
structure SheafOfModules.LocalSectionData where
  /-- the index type of the covering -/
  I : Type w
  /-- a family of objects which cover the terminal object -/
  X : I → C
  coversTop : J.CoversTop X
  /-- the data of sections of `M` over `X i` -/
  sections (i : I) : (M.over (X i)).Sections

/-- `σ : M.Sections` is finite type if the index type `σ.I` is finite. -/
class SheafOfModules.Sections.IsFiniteType (σ : M.Sections) : Prop where
  finite : Finite σ.I := by infer_instance

class SheafOfModules.LocalSectionData.IsFiniteType (p : M.LocalSectionData) : Prop where
  isFiniteType (i : p.I) : (p.sections i).IsFiniteType := by infer_instance

/-- The epimorphism `free σ.I ⟶ M` given by `σ : M.GeneratingSections`. -/
noncomputable abbrev SheafOfModules.Sections.π (σ : M.Sections) :=
  M.freeHomEquiv.symm σ.s

/-- A sheaf of modules is of finite type if locally, it is generated by finitely
many sections. -/
class SheafOfModules.IsCoherent (M : SheafOfModules.{u} R) : Prop where
  finiteType : M.IsFiniteType
  forall_localSectionData (M) : --todo: should we combine the foralls?
    ∀ σ : M.LocalSectionData.{u'}, (∀ i, (σ.sections i).IsFiniteType) →
      ∀ i, (Limits.kernel (σ.sections i).π).IsFiniteType

variable (R) in
def cohProp : CategoryTheory.ObjectProperty (SheafOfModules.{u} R) := by
  intro M
  exact M.IsCoherent

variable {M} in
def SheafOfModules.Sections.map {N : SheafOfModules.{u} R} (σ : N.Sections)
    (i : N ⟶ M) : M.Sections where
  I := σ.I
  s j := sectionsMap i (σ.s j)

variable {M} in
noncomputable
def SheafOfModules.LocalSectionData.map {N : SheafOfModules.{u} R} (σ : N.LocalSectionData.{w})
    (i : N ⟶ M) : M.LocalSectionData.{w} where
  I := σ.I
  X := σ.X
  coversTop := σ.coversTop
  sections j := (σ.sections j).map (i.over (σ.X j))

theorem finitetypesubsheaf (h : SheafOfModules.IsCoherent M) (N : SheafOfModules.{u} R) {i : N ⟶ M}
  (hi : Mono i) (hN : N.IsFiniteType) : SheafOfModules.IsCoherent N := by
  constructor
  · exact hN
  intro σ h1 j
  let U := σ.X j
  -- have covers := σ.coversTop U
  obtain ⟨genN, fingenN⟩ := hN
  have kerfin := h.forall_localSectionData (σ.map i) (fun _ => ⟨(h1 _).1⟩) j
  have compi : SheafOfModules.Sections.π (N.over (σ.X j)) (σ.sections j) ≫ i.over U =
      SheafOfModules.Sections.π (M.over ((σ.map i).X j)) ((σ.map i).sections j) := by
    sorry
  rw [← compi] at kerfin

  --intro σ h1 i
  --have h2 := h1 i




  sorry




variable [HasSheafify J AddCommGrpCat.{u}]

open ZeroObject

lemma
noncomputable instance : (cohProp R).ContainsZero where
  exists_zero := by
    use 0
    constructor
    · exact Limits.isZero_zero (SheafOfModules R)
    · constructor
      · --put a lemma for first condition: zero object is of fintie type
      · --put lemma for second condition: kernel is of finite type
 sorry



noncomputable instance : (cohProp R).IsClosedUnderKernels where
  kernels_le := by
    intro M hM
    obtain ⟨ A, ker ⟩ := hM
  sorry



noncomputable instance : (cohProp R).IsClosedUnderCokernels := by
  sorry

noncomputable instance : (cohProp R).IsClosedUnderFiniteProducts := by
  sorry

noncomputable instance : Abelian (cohProp R).FullSubcategory := by
  infer_instance

end
