
module

public import Mathlib.Algebra.Category.ModuleCat.Sheaf.Quasicoherent

public import Mathlib.Algebra.Category.ModuleCat.Sheaf.Generators

universe u

variable {C : Type u} [CategoryTheory.Category.{u, u} C]
  {J : CategoryTheory.GrothendieckTopology C}
  {R : CategoryTheory.Sheaf J RingCat} (M : SheafOfModules R)
  [∀ (X : C), CategoryTheory.HasWeakSheafify (J.over X) AddCommGrpCat]
  [∀ (X : C), (J.over X).WEqualsLocallyBijective AddCommGrpCat]


/-- The data of local generators of a sheaf of modules is finite type if
each family of generators is finite type. -/
class LocalGeneratorsData.IsFiniteType (p : M.LocalGeneratorsData) : Prop where
  isFiniteType (i : p.I) : (p.generators i).IsFiniteType := by infer_instance

/-- A sheaf of modules is of finite type if locally, it is generated by finitely
many sections. -/
class IsFiniteType (M : SheafOfModules.{u} R) : Prop where
  exists_localGeneratorsData (M) :
    ∃ (σ : (M.LocalGeneratorsData.{u})), σ.IsFiniteType

-- /-- A sheaf of modules is of finite type if locally, it is generated by finitely
-- many sections. -/
-- class IsCoherent (M : SheafOfModules.{u} R) : Prop where
--   finiteType : M.IsFiniteType
--   forall_localGeneratorsData (M) : --todo: should we combine the foralls?
--     ∀ (σ : (M.LocalGeneratorsData.{u})), (∀ i, (σ.generators i).IsFiniteType) →
--       ∀ i, ((CategoryTheory.Limits.kernel  (σ.generators i).π)).IsFiniteType

--todo: instantiate sections (delete epi from generatingsections) + make localgeneratordata depend on sections

/-- The type of sections which doesn't necessarily generate a sheaf of modules. -/
structure SheafOfModules.Sections where
  /-- the index type for the sections -/
  I : Type u
  /-- a family of sections which generate the sheaf of modules -/
  s : I → M.sections

/-- The data of generating sections of the restriction of a sheaf of modules
over a covering of the terminal object. -/
structure SheafOfModules.LocalSectionData where
  /-- the index type of the covering -/
  I : Type u
  /-- a family of objects which cover the terminal object -/
  X : I → C
  coversTop : J.CoversTop X
  /-- the data of sections of `M` over `X i` which generate `M.over (X i)` -/
  sections (i : I) : (M.over (X i)).Sections

/-- `σ : M.GeneratingSections` is finite type if the index type `σ.I` is finite. -/
class SheafOfModules.Sections.IsFiniteType (σ : M.Sections) : Prop where
  finite : Finite σ.I := by infer_instance

class SheafOfModules.LocalSectionData.IsFiniteType (p : M.LocalSectionData) : Prop where
  isFiniteType (i : p.I) : (p.sections i).IsFiniteType := by infer_instance

/-- The epimorphism `free σ.I ⟶ M` given by `σ : M.GeneratingSections`. -/
noncomputable abbrev SheafOfModules.Sections.π
    [CategoryTheory.HasWeakSheafify J AddCommGrpCat]
    [J.WEqualsLocallyBijective AddCommGrpCat]
    (σ : M.Sections) :=
  M.freeHomEquiv.symm σ.s

/-- A sheaf of modules is of finite type if locally, it is generated by finitely
many sections. -/
class IsCoherent (M : SheafOfModules.{u} R)
    [∀ (σ : (M.LocalSectionData.{u})), ∀ i, ∀ (X : CategoryTheory.Over (σ.X i)), CategoryTheory.HasWeakSheafify ((J.over (σ.X i)).over X) AddCommGrpCat]
    [∀ (σ : (M.LocalSectionData.{u})), ∀ i, ∀ (X : CategoryTheory.Over (σ.X i)), ((J.over (σ.X i)).over X).WEqualsLocallyBijective AddCommGrpCat] : Prop where
  finiteType : M.IsFiniteType
  forall_localSectionData (M) : --todo: should we combine the foralls?
    ∀ (σ : (M.LocalSectionData.{u})), (∀ i, (σ.sections i).IsFiniteType) →
      ∀ i, ((CategoryTheory.Limits.kernel  (σ.sections i).π)).IsFiniteType
